"""add monthly report narrative and author columns

Revision ID: a2078873f19e
Revises: 4dd2fbc94a04
Create Date: 2026-09-25 12:38:27.008839

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2078873f19e'
down_revision = '4dd2fbc94a04'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('monthly_reports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('key_achievements', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('difficulties_summary', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('action_plan', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('created_by_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_monthly_reports_created_by_id_users', 'users', ['created_by_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('monthly_reports', schema=None) as batch_op:
        batch_op.drop_constraint('fk_monthly_reports_created_by_id_users', type_='foreignkey')
        batch_op.drop_column('created_by_id')
        batch_op.drop_column('action_plan')
        batch_op.drop_column('difficulties_summary')
        batch_op.drop_column('key_achievements')

    # ### end Alembic commands ###
